version: '3.2'

services:
  db:
    image: postgres:14
    environment: &common-environment
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-coding-challenge}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: -p 5432
    ports:
      - "5434:5432"
