version: '3.8'

services:
  db:
    image: postgres:14
    environment: &common-environment
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-coding-challenge}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - ./_postgres-data:/var/lib/postgresql/data
    command: -p 5432
    ports:
      - "5434:5432"

  runnerenv:
    build:
      context: .
      dockerfile: EnvDockerfile
      target: runnerenv
    tty: true
    mem_limit: 50m
    mem_reservation: 20m
    volumes:
      - codes:/tmp:z
      - ./keys:/keys

  go_server:
    build:
      context: .
    env_file: ./.env
    ports:
      - "8080:8080"
      - "443:443"
    command: bash -c 'ssh-keyscan runnerenv > ~/.ssh/known_hosts && /go/app/scripts/wait-for-it.sh $POSTGRES_HOSTNAME:$POSTGRES_PORT && /go/app/coding-challenge'
    depends_on:
      - db
      - runnerenv
    volumes:
      - codes:/tmp:z
      - ./keys:/root/.ssh:z

volumes:
  codes:
