version: '3.8'

services:
  db:
    image: postgres:14
    environment: &common-environment
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-coding-challenge}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - ./_postgres-data:/var/lib/postgresql/data
    command: -p 5432
    ports:
      - "5434:5432"

  runnerenv:
    image: ghcr.io/toggle-corp/code-runner:master
    tty: true
    mem_limit: 50m
    mem_reservation: 20m
    volumes:
      - codes:/tmp:z
      - ./keys:/keys

  go_server:
    image: ghcr.io/toggle-corp/coding-challenges:master
    env_file: ./.env
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - db
      - runnerenv
    volumes:
      - codes:/tmp:z
      - ./keys:/root/.ssh:z
      - ./certs:/certs:z

volumes:
  codes:
